'use strict';

module.exports = {
  async up (queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
    await queryInterface.bulkInsert('Cards', [{
      color: 'red',
      value: '0',
      special: false
    }, {
      color: 'red',
      value: '1',
      special: false
    }, {
      color: 'red',
      value: '2',
      special: false
    }, {
      color: 'red',
      value: '3',
      special: false
    }, {
      color: 'red',
      value: '4',
      special: false
    }, {
      color: 'red',
      value: '5',
      special: false
    }, {
      color: 'red',
      value: '6',
      special: false
    }, {
      color: 'red',
      value: '7',
      special: false
    }, {
      color: 'red',
      value: '8',
      special: false
    }, {
      color: 'red',
      value: '9',
      special: false
    }, {
      color: 'red',
      value: '1',
      special: false
    }, {
      color: 'red',
      value: '2',
      special: false
    }, {
      color: 'red',
      value: '3',
      special: false
    }, {
      color: 'red',
      value: '4',
      special: false
    }, {
      color: 'red',
      value: '5',
      special: false
    }, {
      color: 'red',
      value: '6',
      special: false
    }, {
      color: 'red',
      value: '7',
      special: false
    }, {
      color: 'red',
      value: '8',
      special: false
    }, {
      color: 'red',
      value: '9',
      special: false
    }, {
      color: 'blue',
      value: '0',
      special: false
    }, {
      color: 'blue',
      value: '1',
      special: false
    }, {
      color: 'blue',
      value: '2',
      special: false
    }, {
      color: 'blue',
      value: '3',
      special: false
    }, {
      color: 'blue',
      value: '4',
      special: false
    }, {
      color: 'blue',
      value: '5',
      special: false
    }, {
      color: 'blue',
      value: '6',
      special: false
    }, {
      color: 'blue',
      value: '7',
      special: false
    }, {
      color: 'blue',
      value: '8',
      special: false
    }, {
      color: 'blue',
      value: '9',
      special: false
    }, {
      color: 'blue',
      value: '1',
      special: false
    }, {
      color: 'blue',
      value: '2',
      special: false
    }, {
      color: 'blue',
      value: '3',
      special: false
    }, {
      color: 'blue',
      value: '4',
      special: false
    }, {
      color: 'blue',
      value: '5',
      special: false
    }, {
      color: 'blue',
      value: '6',
      special: false
    }, {
      color: 'blue',
      value: '7',
      special: false
    }, {
      color: 'blue',
      value: '8',
      special: false
    }, {
      color: 'blue',
      value: '9',
      special: false
    }, {
      color: 'green',
      value: '0',
      special: false
    }, {
      color: 'green',
      value: '1',
      special: false
    }, {
      color: 'green',
      value: '2',
      special: false
    }, {
      color: 'green',
      value: '3',
      special: false
    }, {
      color: 'green',
      value: '4',
      special: false
    }, {
      color: 'green',
      value: '5',
      special: false
    }, {
      color: 'green',
      value: '6',
      special: false
    }, {
      color: 'green',
      value: '7',
      special: false
    }, {
      color: 'green',
      value: '8',
      special: false
    }, {
      color: 'green',
      value: '9',
      special: false
    }, {
      color: 'green',
      value: '1',
      special: false
    }, {
      color: 'green',
      value: '2',
      special: false
    }, {
      color: 'green',
      value: '3',
      special: false
    }, {
      color: 'green',
      value: '4',
      special: false
    }, {
      color: 'green',
      value: '5',
      special: false
    }, {
      color: 'green',
      value: '6',
      special: false
    }, {
      color: 'green',
      value: '7',
      special: false
    }, {
      color: 'green',
      value: '8',
      special: false
    }, {
      color: 'green',
      value: '9',
      special: false
    }, {
      color: 'yellow',
      value: '0',
      special: false
    }, {
      color: 'yellow',
      value: '1',
      special: false
    }, {
      color: 'yellow',
      value: '2',
      special: false
    }, {
      color: 'yellow',
      value: '3',
      special: false
    }, {
      color: 'yellow',
      value: '4',
      special: false
    }, {
      color: 'yellow',
      value: '5',
      special: false
    }, {
      color: 'yellow',
      value: '6',
      special: false
    }, {
      color: 'yellow',
      value: '7',
      special: false
    }, {
      color: 'yellow',
      value: '8',
      special: false
    }, {
      color: 'yellow',
      value: '9',
      special: false
    }, {
      color: 'yellow',
      value: '1',
      special: false
    }, {
      color: 'yellow',
      value: '2',
      special: false
    }, {
      color: 'yellow',
      value: '3',
      special: false
    }, {
      color: 'yellow',
      value: '4',
      special: false
    }, {
      color: 'yellow',
      value: '5',
      special: false
    }, {
      color: 'yellow',
      value: '6',
      special: false
    }, {
      color: 'yellow',
      value: '7',
      special: false
    }, {
      color: 'yellow',
      value: '8',
      special: false
    }, {
      color: 'yellow',
      value: '9',
      special: false
    }, {
      color: 'red',
      value: 'skip',
      special: true
    }, {
      color: 'red',
      value: 'skip',
      special: true
    }, {
      color: 'red',
      value: 'reverse',
      special: true
    }, {
      color: 'red',
      value: 'reverse',
      special: true
    }, {
      color: 'red',
      value: 'plus2',
      special: true
    }, {
      color: 'red',
      value: 'plus2',
      special: true
    }, {
      color: 'blue',
      value: 'skip',
      special: true
    }, {
      color: 'blue',
      value: 'skip',
      special: true
    }, {
      color: 'blue',
      value: 'reverse',
      special: true
    }, {
      color: 'blue',
      value: 'reverse',
      special: true
    }, {
      color: 'blue',
      value: 'plus2',
      special: true
    }, {
      color: 'blue',
      value: 'plus2',
      special: true
    }, {
      color: 'green',
      value: 'skip',
      special: true
    }, {
      color: 'green',
      value: 'skip',
      special: true
    }, {
      color: 'green',
      value: 'reverse',
      special: true
    }, {
      color: 'green',
      value: 'reverse',
      special: true
    }, {
      color: 'green',
      value: 'plus2',
      special: true
    }, {
      color: 'green',
      value: 'plus2',
      special: true
    }, {
      color: 'yellow',
      value: 'skip',
      special: true
    }, {
      color: 'yellow',
      value: 'skip',
      special: true
    }, {
      color: 'yellow',
      value: 'reverse',
      special: true
    }, {
      color: 'yellow',
      value: 'reverse',
      special: true
    }, {
      color: 'yellow',
      value: 'plus2',
      special: true
    }, {
      color: 'yellow',
      value: 'plus2',
      special: true
    }, {
      color: 'wild',
      value: 'plus4choose',
      special: true
    }, {
      color: 'wild',
      value: 'plus4choose',
      special: true
    }, {
      color: 'wild',
      value: 'plus4choose',
      special: true
    }, {
      color: 'wild',
      value: 'plus4choose',
      special: true
    }, {
      color: 'wild',
      value: 'choose',
      special: true
    }, {
      color: 'wild',
      value: 'choose',
      special: true
    }, {
      color: 'wild',
      value: 'choose',
      special: true
    }, {
      color: 'wild',
      value: 'choose',
      special: true
    }, {
      color: 'wild',
      value: 'swap',
      special: true
    }, {
      color: 'wild',
      value: 'swap',
      special: true
    }, {
      color: 'wild',
      value: 'swap',
      special: true
    }, {
      color: 'wild',
      value: 'swap',
      special: true
    }], {});
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete('card', null, {});
  }
};
